#pragma once
#include "alias.hpp"

namespace Core {

// These keycodes correspond to windows keycodes
enum class KeyCode {
    UNKNOWN   ,
    ESCAPE    ,
    BACKSPACE ,
    TAB       ,
    ENTER     ,
    SPACE     ,
    QUOTE     ,
    PLUS      ,
    COMMA     ,
    MINUS     ,
    PERIOD    ,
    KEY_0     ,
    KEY_1     ,
    KEY_2     ,
    KEY_3     ,
    KEY_4     ,
    KEY_5     ,
    KEY_6     ,
    KEY_7     ,
    KEY_8     ,
    KEY_9     ,
    COLON     ,
    ANGLE     ,
    QUESTION  ,
    LBRACKET  ,
    RBRACKET  ,
    TILDE     ,
    A         ,
    B         ,
    C         ,
    D         ,
    E         ,
    F         ,
    G         ,
    H         ,
    I         ,
    J         ,
    K         ,
    L         ,
    M         ,
    N         ,
    O         ,
    P         ,
    Q         ,
    R         ,
    S         ,
    T         ,
    U         ,
    V         ,
    W         ,
    X         ,
    Y         ,
    Z         ,
    KEY_DELETE,
    CAPSLOCK  ,
    F1        ,
    F2        ,
    F3        ,
    F4        ,
    F5        ,
    F6        ,
    F7        ,
    F8        ,
    F9        ,
    F10       ,
    F11       ,
    F12       ,
    F13       ,
    F14       ,
    F15       ,
    F16       ,
    F17       ,
    F18       ,
    F19       ,
    F20       ,
    F21       ,
    F22       ,
    F23       ,
    F24       ,
    PRINT     ,
    SCRLK     ,
    PAUSE     ,
    INSERT    ,
    HOME      ,
    PGUP      ,
    END       ,
    PGDWN     ,
    RIGHT     ,
    LEFT      ,
    DOWN      ,
    UP        ,
    NUMLOCK   ,
    DIVIDE    ,
    MULTIPLY  ,
    SUBTRACT  ,
    ADD       ,
    PAD_0     ,
    PAD_1     ,
    PAD_2     ,
    PAD_3     ,
    PAD_4     ,
    PAD_5     ,
    PAD_6     ,
    PAD_7     ,
    PAD_8     ,
    PAD_9     ,
    LWIN      ,
    RWIN      ,
    CTRL      ,
    SHIFT     ,
    ALT       ,

    count
};

KeyCode WinKeyToKeyCode( u32 winKey );
const char* KeyCodeToString( KeyCode keycode );

}
